### ISSUE TITLE
got error, 

### ISSUE THREAD

**Issue by bloserda** [SwiftDeal/Musik#2]
![error](https://user-images.githubusercontent.com/33650702/32767553-74ebfb5a-c946-11e7-8ffb-bd5a11188950.png)

how to fix it? i use xampp.
Thanks before

**Comment by Hemant-Mann** [comment]
Hi @bloserda 
This is an old project so php code might generate some warnings so plz do this
`error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING)`

Also I have updated the master branch could you try with the latest pull?

**Comment by bloserda** [comment]
Thanks @Hemant-Mann for updated the master branch, and i attach that line you said at index.php, but i've got error, here the screenshot :

![issues2](https://user-images.githubusercontent.com/33650702/33157057-d033eee0-d031-11e7-80b4-3e386c43b88a.png)


so, tell me where i must attach that line.

nb : Line = error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);

**Comment by Hemant-Mann** [comment]
Hi @bloserda  I have create a pull request #3 for this issue
I have tested the pull request locally and it works for me
plz verify it from your end

**Comment by Hemant-Mann** [comment]
Closing the issue
