### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by chilledguru** [SwiftDeal/Musik#4]
Dear Friend,

1st of all, please include complete installation steps on in the readme.md 

i have installed it at http://downfreemp3.ga and links seems not working, please advise.

if possible, please let me know if i want to install it on a cpanel account.

**Comment by Hemant-Mann** [comment]
Hi @chilledguru 

So this is an old project but the installation steps were simple enough as I provided an init script as well

After opening any link on http://downfreemp3.ga/ I see 404 error is there

Please do these 2 things
- Enable mod rewrite module apache
- Check that **AllowOverride** is set to **All** in apache conf

Let me know if this helps

**Comment by chilledguru** [comment]
than you for the swift response, i have installed it on a cpanel account where youtube-dl and ffmpeg is already available.

there are no such config for me to set, can you please tell me the steps to make it work on cpanel.

or 

let me know the complete steps to install apache and its config, mysql and db/user create and grant permissions to make it working so i can get cloud node ubuntu 16.04 installed and get it done.

Many thanks

**Comment by chilledguru** [comment]
or i might need htaccess containing rules to make it work, if yes, please do the needful

**Comment by Hemant-Mann** [comment]
@chilledguru 

Please verify whether your apache conf allows to read the .htaccess file supplied with this repository

https://stackoverflow.com/questions/18740419/how-to-set-allowoverride-all

**Comment by chilledguru** [comment]
Hi Hemant,

thank you again for looking and time. yes, i have already done this but seems not working, i have also confirmed that AllowOverride All is already in place in apache config.

can you please send me the working version for cpanel hosting?

**Comment by chilledguru** [comment]
Hi Hemant,

there was issue with htaccess and i fixed it, please let me know what how to access admin area and what is the user pass?

**Comment by Hemant-Mann** [comment]
Hmm good question

so actually only admins can access admin area

You can create a account using the register page and then mark yourself an admin using PHPMyadmin or Mysql

**Comment by chilledguru** [comment]
Thank you hemant,

a quick fix for mp3 and video download. i dont know from where mp3s are coming but if the songs are being fetch from youtube, i want to add iframe from https://yt-mp3s.com and for videos (as they are from youtube)... also iframe from https://yt-mp3s.com

please help me add this and let me know the file location to edit

**Comment by chilledguru** [comment]
or if possible, please update the repo content with your currently working http://playmusic.net so we can have updated code and YTDownload plugin etc.

**Comment by Hemant-Mann** [comment]
@chilledguru 

Go to application/controllers/home.php -> download method

That contains the code to download a song

A youtube video is downloaded with the help of youtube-dl and then converted to mp3 using ffmpeg
https://github.com/Hemant-Mann/YTDownloader

YTDownloader code is shipped with this repository and can be found in application/libraries/YTDownloader folder
